#ifndef CONFIG_H
#define CONFIG_H

#ifndef NRF_DFU_BLE_ADV_NAME
#define NRF_DFU_BLE_ADV_NAME "ECG_DFU"
#endif
#define BLEDIS_MANUFACTURER "ddB0515"
#define BLEDIS_MODEL "nRF52840 Board"
  
#define APP_USBD_VID 0x239A
#define APP_USBD_PID 0x0029
#endif

#ifndef NRF_DFU_BL_ALLOW_DOWNGRADE
#define NRF_DFU_BL_ALLOW_DOWNGRADE 1
#endif

